project(rx-bench)

find_package(benchmark REQUIRED)
find_package(ctre REQUIRED)
find_package(re2 REQUIRED)
find_package(Boost REQUIRED)
find_package(pcre2 OPTIONAL)

add_executable(bench-simple)
target_sources(bench-simple PRIVATE simple.cpp)
target_compile_options(bench-simple PRIVATE -march=native)
target_link_libraries(bench-simple PRIVATE static_regex benchmark::benchmark)
set_target_properties(bench-simple PROPERTIES FOLDER benchmarks)

list(APPEND BENCH_TYPES sv cstr dq list)
list(LENGTH BENCH_TYPES BENCH_TYPES_SIZE)
MATH(EXPR BENCH_TYPES_SIZE "${BENCH_TYPES_SIZE}-1")

foreach(INDEX RANGE ${BENCH_TYPES_SIZE})
    list(GET BENCH_TYPES ${INDEX} SUFFIX)
    set(CURRENT_NAME "bench-search-${SUFFIX}")
    add_executable(${CURRENT_NAME})
    target_sources(${CURRENT_NAME} PRIVATE search.cpp)
    target_compile_options(${CURRENT_NAME} PRIVATE -march=native)
    target_compile_definitions(${CURRENT_NAME} PRIVATE SRX_BENCH_SEARCH_MODE=${INDEX})
    target_link_libraries(${CURRENT_NAME} PRIVATE static_regex benchmark::benchmark)
    set_target_properties(${CURRENT_NAME} PROPERTIES FOLDER benchmarks)
endforeach()

add_executable(bench-rtbuild)
target_sources(bench-rtbuild PRIVATE rtbuild.cpp)
target_compile_options(bench-rtbuild PRIVATE -O0)
target_link_libraries(bench-rtbuild PRIVATE static_regex benchmark::benchmark)
set_target_properties(bench-rtbuild PROPERTIES FOLDER benchmarks)

add_executable(bench-cstropt)
target_sources(bench-cstropt PRIVATE cstropt.cpp)
target_compile_options(bench-cstropt PRIVATE -march=native)
target_link_libraries(bench-cstropt PRIVATE static_regex benchmark::benchmark)
set_target_properties(bench-cstropt PROPERTIES FOLDER benchmarks)

add_executable(bench-compare-long)
target_sources(bench-compare-long PRIVATE compare_long.cpp)
target_compile_options(bench-compare-long PRIVATE -march=native)
target_link_libraries(bench-compare-long PRIVATE static_regex benchmark::benchmark re2::re2 pcre2-8)
set_target_properties(bench-compare-long PROPERTIES FOLDER benchmarks)