project(rx-tools)

file(GLOB TOOL_SOURCES "*.cpp")
foreach(TOOL_SOURCE ${TOOL_SOURCES})
    get_filename_component(TARGET_NAME ${TOOL_SOURCE} NAME_WE)
    string(REGEX REPLACE  "^_" "" TARGET_NAME ${TARGET_NAME})
    string(REGEX REPLACE  "_+" "-" TARGET_NAME ${TARGET_NAME})
    add_executable(${TARGET_NAME})
    target_sources(${TARGET_NAME} PRIVATE ${TOOL_SOURCE})
    target_compile_options(${TARGET_NAME} PRIVATE -Wall -Wextra -Wnrvo -Wno-maybe-musttail-local-addr)
    target_link_libraries(${TARGET_NAME} PUBLIC static_regex)
    set_target_properties(${TARGET_NAME} PROPERTIES FOLDER tools)
endforeach()
